export const FoodTypes = [
    { value: 'Brasileira', label: 'Brasileira' },
    { value: 'Picante', label: 'Picante' },
    { value: 'Mexicana', label: 'Mexicana' },
    { value: 'Japonesa', label: 'Japonesa' },
    { value: 'Tailandesa', label: 'Tailandesa' },
    { value: 'Chinesa', label: 'Chinesa' },
    { value: 'Indiana', label: 'Indiana' },
    { value: 'Italiana', label: 'Italiana' },
    { value: 'Lanches', label: 'Lanches' },
    { value: 'Pizza', label: 'Pizza' },
    { value: 'Churrasco', label: 'Churrasco' },
    { value: 'Saudável', label: 'Saudável' },
    { value: 'Bebidas', label: 'Bebidas' },
    { value: 'Açaí', label: 'Açaí' },
    { value: 'Árabe', label: 'Árabe' },
    { value: 'Petiscos', label: 'Petiscos' },
    { value: 'Sobremesas', label: 'Sobremesas' },
    { value: 'Americana', label: 'Americana' },
]