export const lightTheme = {
  title: 'light',

  colors: {
    backgroundColor: '#F2F2F2',
    primary: '#071A40',
    secondary: '#01A5A5',
    textColor: '#031626',
    greenColor: '#00D982',
    redColor: '#C90000',
    blackColor: '#000',
    whiteColor: '#FFF',
    sucessInput: '#07D9D9',
    darkGray: '#A2A2A2',
    backgroundCard: '#031626',
    textCardColor: '#FFF',
    colorInputBorder: '#DDDDDD',
    backgroundLogin: '#F2F2F2',
    verifyCodeColor: '#BFBABA',
    verifyCodeSpanColor: '#000000',
    textColorModal: '#031626',
    textColorSideBar: '#FFF',
    textColorSideBarHover: '#071A40',
    inputTextColor: '#525252',
    borderSearchButton: '#D9D9D9',
    backgroundFile: '#D9D9D9',
    buttonDisabled: '#DDDDDD',
    borderOrder: '#B7B7B7',
    TitleOrder: '#625858',
    borderCard: '#6B6B6B',
    textExpandCard: '#979797',
  }
};

export const darkTheme = {
  title: 'dark',

  colors: {
    backgroundColor: '#031626',
    primary: '#07D9D9',
    secondary: '#01A5A5',
    textColor: '#FFFFFF',
    greenColor: '#00D982',
    redColor: '#C90000',
    blackColor: '#000',
    whiteColor: '#FFF',
    sucessInput: '#07D9D9',
    darkGray: '#A2A2A2',
    backgroundCard: '#071A40',
    textCardColor: '#07D9D9',
    colorInputBorder: '#DDDDDD',
    backgroundLogin: '#F2F2F2',
    verifyCodeColor: '#FFFFFF',
    verifyCodeSpanColor: '#FFFFFF',
    textColorModal: '#031626',
    textColorSideBar: '#071A40',
    textColorSideBarHover: '#07D9D9',
    inputTextColor: '#525252',
    borderSearchButton: '#D9D9D9',
    backgroundFile: '#D9D9D9',
    buttonDisabled: '#DDDDDD',
    borderOrder: '#FFFFFF',
    TitleOrder: '#FFFFFF',
    borderCard: '#FFFFFF',
    textExpandCard: '#07D9D9',
  }
};